G_School/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.messages.context_processors import messages

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('GSchoolApp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GSchoolApp/models.py
from itertools import count
from django.db import models
from django.db.models import Sum


# Create your models here.
class Classe(models.Model):
    nom = models.CharField(max_length=35, unique=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.nom
    
    
class Personne(models.Model):
    Genre = (
        ('M', 'Masculin'),
        ('F', 'Feminin'),
    )
    prenom = models.CharField('Prénom', max_length=150)
    nom = models.CharField('Nom', max_length=150)
    date_naissance = models.DateField('Date de naissance', max_length=150)
    lieu_naissance = models.TextField('Lieu de naissance', max_length=150)
    genre = models.CharField(max_length=1, choices=Genre)
    adresse = models.TextField('Adresse', max_length=150)
    phone_number = models.CharField('Numéro téléphone', max_length=10)
    email = models.EmailField('Adresse Email', max_length=50)
    photo = models.ImageField(upload_to="photo", blank=True, null=True)

    class Meta:
        abstract = True

    def __str__(self):
        return f"{self.prenom} {self.nom}"

    
class Eleve(Personne):
    Status = (
        ('Nouveau', 'Nouveau élève'),
        ('Ancien', 'Ancien élève'),
    )
    matricule = models.CharField(max_length=20, unique=True)
    status = models.CharField(max_length=32, choices=Status)
    classes = models.ForeignKey(Classe, on_delete=models.CASCADE)  # Utilisez ForeignKey pour la classe
    date_inscription = models.DateField(default=True)
    
    @property
    def moyenne(self):
        """
        Calcule la moyenne des notes de l'élève.

        Returns:
            float: La moyenne des notes de l'élève.
        """

        notes = Note.objects.filter(eleve=self)
        somme_notes = notes.aggregate(somme=Sum('note'))['somme']
        nombre_notes = notes.count()

        if nombre_notes == 0:
            return 0.0

        moyenne = somme_notes / nombre_notes
        return moyenne

    def __str__(self):
        return f"{self.prenom} {self.nom}"
    
    def save(self, *args, **kwargs):
        # Générez un matricule unique en fonction de l'ID de l'objet
        if not self.matricule:
            self.matricule = f"ELE-{self.id}"
        super(Eleve, self).save(*args, **kwargs)


class Parent(models.Model):
    nom_pere = models.CharField('Nom du Père', max_length=150)
    nom_mere = models.CharField('Nom de la Mère', max_length=150)
    phone_number1 = models.CharField(max_length=10)
    phone_number2 = models.CharField(max_length=10)
    adresse = models.TextField(max_length=150)
    eleves = models.ManyToManyField(Eleve)

    
class Enseignant(Personne):
    Categorie = (
        ('Per', 'Permanent'),
        ('Vac', 'Vacataire'),
    )
    matricule = models.CharField(max_length=20, unique=True)
    poste = models.CharField(max_length=60)
    type_poste = models.CharField(max_length=60, choices=Categorie)
    diplome = models.CharField(max_length=60)
    specialite = models.CharField(max_length=70)
    classes = models.ManyToManyField('Classe')
    fonction = models.CharField(max_length=60, blank=True, null=True)

    def save(self, *args, **kwargs):
        # Générez un matricule unique en fonction de l'ID de l'objet
        if not self.matricule:
            self.matricule = f"ENS-{self.id}"
        super(Enseignant, self).save(*args, **kwargs)
    def __str__(self):
        return f"{self.prenom} {self.nom} ({self.specialite})"
    
    
class Domain(models.Model):
    nom = models.CharField(max_length=32)

    def __str__(self):
        return self.nom
    
class Matiere(models.Model):
    nom = models.CharField(max_length=60, unique=True)
    description = models.TextField(max_length=180)
    coefficient = models.PositiveIntegerField()
    domain = models.ForeignKey(Domain, on_delete=models.CASCADE)
    classes = models.ManyToManyField('Classe')

    def __str__(self):
        return self.nom
    
class Note(models.Model):
    eleve = models.ForeignKey(Eleve, on_delete=models.CASCADE)
    matiere = models.ForeignKey(Matiere, on_delete=models.CASCADE)
    note = models.FloatField(default=0.0)
    date = models.DateField()
    semestre = models.ForeignKey('Semestre', on_delete=models.CASCADE)
    classe = models.ForeignKey(Classe, on_delete=models.CASCADE)

    def __str__(self):
        return f"Note de {self.eleve.prenom} {self.eleve.nom} en {self.matiere.nom} - Classe: {self.eleve.classes.nom}"
    
    
class Emploi_du_temps(models.Model):
    jour = models.CharField(max_length=60)
    heure_debut = models.TimeField()
    heure_fin = models.TimeField()
    classe = models.ForeignKey(Classe, on_delete=models.CASCADE)
    matiere = models.ForeignKey(Matiere, on_delete=models.CASCADE)
    enseignant = models.ForeignKey(Enseignant, on_delete=models.CASCADE)
    date = models.DateField()
    
    # classer les enregistrements par classe en plus de les regrouper par jour
def group_by_day_and_class(self):
        return (
            Emploi_du_temps.objects
            .values('jour', 'classe__nom')  # Remarquez 'classe__nom' pour obtenir le nom de la classe
            .annotate(count=count('jour'))
            .order_by('jour', 'classe__nom')  # Remarquez 'classe__nom' ici aussi
        )



class Evaluation(models.Model):
    Type_eva = (
        ('Contrôle', 'Contrôle Continu'),
        ('Exam', 'Examen'),
    )
    classe = models.ForeignKey(Classe, on_delete=models.CASCADE)
    matiere = models.ForeignKey(Matiere, on_delete=models.CASCADE)
    type_d_evaluation = models.CharField(max_length=55, choices=Type_eva)
    note = models.FloatField()
    semestre = models.ForeignKey('Semestre', on_delete=models.CASCADE)
    jour = models.DateTimeField()

class Bulletin(models.Model):
    eleve = models.ForeignKey(Eleve, on_delete=models.CASCADE)
    annee_scolaire = models.ForeignKey('Annee_scolaire', on_delete=models.CASCADE)
    matieres = models.ManyToManyField(Matiere)
    notes = models.FloatField(default=1.0)
    semestre = models.ForeignKey('Semestre', on_delete=models.CASCADE)


class Cycle(models.Model):
    nom = models.CharField(max_length=55, unique=True)
    durée = models.DateField()
    classes = models.ManyToManyField(Classe)

    def __str__(self):
        return self.nom
    

class Annee_scolaire(models.Model):
    debut_annee = models.DateField()
    fin_annee = models.DateField()
    cycles = models.ManyToManyField(Cycle)

class Semestre(models.Model):
    nom = models.CharField(max_length=55, unique=True)
    annee_scolaire = models.ForeignKey(Annee_scolaire, on_delete=models.CASCADE)
    cycles = models.ManyToManyField(Cycle)

    def __str__(self):
        return self.nom

class Absence(models.Model):
    eleves = models.ForeignKey(Eleve, on_delete=models.CASCADE)
    date = models.DateField()
    motif = models.CharField(max_length=200)
    duree = models.DateTimeField()

    def __str__(self):
        return f"{self.eleves} ({self.date}): {self.motif}"

templates/details/detail_annee_scolaire.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    </br></br></br></br>
    <div class="container">
        <h1>Année Scolaire</h1>
        <ul>
            <li><strong>Début de l'année :</strong> {{ annee_scolaire.debut_annee }}</li>
            <li><strong>Fin de l'année :</strong> {{ annee_scolaire.fin_annee }}</li>
            <li><strong>Cycles :</strong>
                {% if annee_scolaire.cycles.exists %}
                    <ul>
                        {% for cycle in annee_scolaire.cycles.all %}
                            <li>{{ cycle.nom }}</li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>Aucun cycle associé à cette année scolaire.</p>
                {% endif %}
            </li>
        </ul>
    </div>
    <a class="btn btn-primary" href="{% url 'liste_annees_scolaires' %}" >Retour à la liste des années scolaires</a>
{% endblock %}

templates/details/detail_bulletins.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <h1>Détail du Bulletin</h1>
    <p>Élève : {{ bulletin.eleve.nom }}</p>
    <p>Année Scolaire : {{ bulletin.annee_scolaire.debut_annee }}/{{ bulletin.annee_scolaire.fin_annee }}</p>

    <h2>Notes par Matière :</h2>
    <ul>
        {% for matiere in matieres %}
            <li>
                {{ matiere.nom }} : {{ matiere.note }}
            </li>
        {% endfor %}
    </ul>

{% endblock %}

templates/details/detail_classe.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    </br></br></br></br>
    <center><h1>Détails de la Classe</h1></center>
    <div class="container">
        <ul class="list-group">
            <li class="list-group-item"><strong>Nom de la Classe:</strong> {{ classe.nom }}</li>
            <li class="list-group-item"><strong>Description:</strong> {{ classe.description }}</li>
            <li class="list-group-item"><strong>Le nombre d'élèves est de :</strong> {{ nombre_eleves }}</li>
        </ul>
        <a class="btn btn-primary mt-3" href="{% url 'liste_classes' %}">Retour à la liste des classes</a>
    </div>
{% endblock  %}
    </br></br>

templates/details/detail_eleve.html
{% extends "base.html" %}
{% load static %}
{% block content %}

</br></br></br></br>
<div class="student-card">
    <h1>Détail de l'Élève</h1>
    <div class="card-content">
        {% if eleve.photo %}
            <img src="{{ eleve.photo.url }}" alt="{{ eleve.nom }} {{ eleve.prenom }}" class="photo-4x4">
        {% else %}
            <p>Aucune photo disponible.</p>
        {% endif %}
        <p><strong>Nom:</strong> {{ eleve.nom }}</p>
        <p><strong>Prénom:</strong> {{ eleve.prenom }}</p>
        <p><strong>Date de naissance:</strong> {{ eleve.date_naissance }}</p>
        <p><strong>Lieu de naissance:</strong> {{ eleve.lieu_naissance }}</p>
        <p><strong>Matricule:</strong> {{ eleve.matricule }}</p>
        <p><strong>Statut:</strong> {{ eleve.status }}</p>
        <p><strong>Classes:</strong> 
            {% for classe in eleve.classes.all %}
                {{ classe.nom }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <!-- Afficher les informations des parents -->
        <h2>Informations des Parents</h2>
        {% for parent in eleve.parent_set.all %}
            <p><strong>Nom du Père:</strong> {{ parent.nom_pere }}</p>
            <p><strong>Nom de la Mère:</strong> {{ parent.nom_mere }}</p>
            <p><strong>Téléphone 1:</strong> {{ parent.phone_number1 }}</p>
            <p><strong>Téléphone 2:</strong> {{ parent.phone_number2 }}</p>
            <p><strong>Adresse:</strong> {{ parent.adresse }}</p>
            <br>
        {% endfor %}

    </div>
    <a class="btn btn-primary" href="{% url 'liste_eleves' %}" >Retour à la liste des élèves</a>
</div>
{% endblock %}

templates/details/detail_enseignant.html
{% extends "base.html" %}
{% load static %}
{% block content %}

</br></br></br></br>
<div class="container">
    <h1>Détails de l'Enseignant</h1>

    {% if enseignant.photo %}
        <img src="{{ enseignant.photo.url }}" alt="{{ enseignant.nom }} {{ enseignant.prenom }}" class="photo-4x4">
    {% else %}
        <p>Aucune photo disponible.</p>
    {% endif %}

    <p><strong>Matricule:</strong> {{ enseignant.matricule }}</p>
    <p><strong>Nom:</strong> {{ enseignant.nom }}</p>
    <p><strong>Prénom:</strong> {{ enseignant.prenom }}</p>
    <p><strong>Poste:</strong> {{ enseignant.poste }}</p>
    <p><strong>Type de Poste:</strong> {{ enseignant.get_type_poste_display }}</p>
    <p><strong>Diplôme:</strong> {{ enseignant.diplome }}</p>
    <p><strong>Spécialité:</strong> {{ enseignant.specialite }}</p>
    <p><strong>Classes:</strong>
        {% for classe in enseignant.classes.all %}
            {{ classe.nom }}
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>

    <a class="btn btn-primary" href="{% url 'liste_enseignant' %}">Retour à la liste des enseignants</a>
</div>

{% endblock %}

templates/details/detail_evaluation.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    </br></br></br></br>
    <center><h1>Détail de l'Évaluation</h1></center>
    <div class="container">
        <ul class="list-group">
            <li class="list-group-item"><strong>Type d'Évaluation:</strong> {{ evaluation.type_d_evaluation }}</li>
            <li class="list-group-item"><strong>Classe:</strong> {{ evaluation.classe }}</li>
            <li class="list-group-item"><strong>Matière:</strong> {{ evaluation.matiere }}</li>
            <li class="list-group-item"><strong>Note:</strong> {{ evaluation.note }}</li>
        </ul>
        <a class="btn btn-primary" href="{% url 'liste_evaluations' %}">Retour à la liste des évaluations</a>
    </div>
    {% endblock  %}

templates/details/detail_matiere.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <title>{{ matiere.nom }}</title>

    </br></br></br></br>
    <div class="container">
        <h1>Bienvenue sur les meilleurs cours en {{ matiere.nom }}</h1>
        <p class="lead">A propos : {{ matiere.description }}</p>

        <!-- Utilisez la classe "row" pour créer une rangée Bootstrap -->
        <div class="row">
            <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4 mt-md-0">
                <div class="course-item">
                    {% if matiere.image %}
                        <img src="{{ matiere.image.url }}" class="img-fluid" alt="{{ matiere.nom }}">
                    {% endif %}
                    <div class="course-content">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4>{{ matiere.nom }}</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <ul class="list-group">
            {% for item in items %}
                <li class="list-group-item">{{ item }}</li>
            {% empty %}
                <li class="list-group-item">Aucun élément disponible.</li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}