G_School/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.messages.context_processors import messages

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('GSchoolApp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GSchoolApp/models.py
from itertools import count
from django.db import models
from django.db.models import Sum


# Create your models here.
class Classe(models.Model):
    nom = models.CharField(max_length=35, unique=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.nom
    
    
class Personne(models.Model):
    Genre = (
        ('M', 'Masculin'),
        ('F', 'Feminin'),
    )
    prenom = models.CharField('Prénom', max_length=150)
    nom = models.CharField('Nom', max_length=150)
    date_naissance = models.DateField('Date de naissance', max_length=150)
    lieu_naissance = models.TextField('Lieu de naissance', max_length=150)
    genre = models.CharField(max_length=1, choices=Genre)
    adresse = models.TextField('Adresse', max_length=150)
    phone_number = models.CharField('Numéro téléphone', max_length=10)
    email = models.EmailField('Adresse Email', max_length=50)
    photo = models.ImageField(upload_to="photo", blank=True, null=True)

    class Meta:
        abstract = True

    def __str__(self):
        return f"{self.prenom} {self.nom}"

    
class Eleve(Personne):
    Status = (
        ('Nouveau', 'Nouveau élève'),
        ('Ancien', 'Ancien élève'),
    )
    matricule = models.CharField(max_length=20, unique=True)
    status = models.CharField(max_length=32, choices=Status)
    classes = models.ForeignKey(Classe, on_delete=models.CASCADE)  # Utilisez ForeignKey pour la classe
    date_inscription = models.DateField(default=True)
    
    @property
    def moyenne(self):
        """
        Calcule la moyenne des notes de l'élève.

        Returns:
            float: La moyenne des notes de l'élève.
        """

        notes = Note.objects.filter(eleve=self)
        somme_notes = notes.aggregate(somme=Sum('note'))['somme']
        nombre_notes = notes.count()

        if nombre_notes == 0:
            return 0.0

        moyenne = somme_notes / nombre_notes
        return moyenne

    def __str__(self):
        return f"{self.prenom} {self.nom}"
    
    def save(self, *args, **kwargs):
        # Générez un matricule unique en fonction de l'ID de l'objet
        if not self.matricule:
            self.matricule = f"ELE-{self.id}"
        super(Eleve, self).save(*args, **kwargs)


class Parent(models.Model):
    nom_pere = models.CharField('Nom du Père', max_length=150)
    nom_mere = models.CharField('Nom de la Mère', max_length=150)
    phone_number1 = models.CharField(max_length=10)
    phone_number2 = models.CharField(max_length=10)
    adresse = models.TextField(max_length=150)
    eleves = models.ManyToManyField(Eleve)

    
class Enseignant(Personne):
    Categorie = (
        ('Per', 'Permanent'),
        ('Vac', 'Vacataire'),
    )
    matricule = models.CharField(max_length=20, unique=True)
    poste = models.CharField(max_length=60)
    type_poste = models.CharField(max_length=60, choices=Categorie)
    diplome = models.CharField(max_length=60)
    specialite = models.CharField(max_length=70)
    classes = models.ManyToManyField('Classe')
    fonction = models.CharField(max_length=60, blank=True, null=True)

    def save(self, *args, **kwargs):
        # Générez un matricule unique en fonction de l'ID de l'objet
        if not self.matricule:
            self.matricule = f"ENS-{self.id}"
        super(Enseignant, self).save(*args, **kwargs)
    def __str__(self):
        return f"{self.prenom} {self.nom} ({self.specialite})"
    
    
class Domain(models.Model):
    nom = models.CharField(max_length=32)

    def __str__(self):
        return self.nom
    
class Matiere(models.Model):
    nom = models.CharField(max_length=60, unique=True)
    description = models.TextField(max_length=180)
    coefficient = models.PositiveIntegerField()
    domain = models.ForeignKey(Domain, on_delete=models.CASCADE)
    classes = models.ManyToManyField('Classe')

    def __str__(self):
        return self.nom
    
class Note(models.Model):
    eleve = models.ForeignKey(Eleve, on_delete=models.CASCADE)
    matiere = models.ForeignKey(Matiere, on_delete=models.CASCADE)
    note = models.FloatField(default=0.0)
    date = models.DateField()
    semestre = models.ForeignKey('Semestre', on_delete=models.CASCADE)
    classe = models.ForeignKey(Classe, on_delete=models.CASCADE)

    def __str__(self):
        return f"Note de {self.eleve.prenom} {self.eleve.nom} en {self.matiere.nom} - Classe: {self.eleve.classes.nom}"
    
    
class Emploi_du_temps(models.Model):
    jour = models.CharField(max_length=60)
    heure_debut = models.TimeField()
    heure_fin = models.TimeField()
    classe = models.ForeignKey(Classe, on_delete=models.CASCADE)
    matiere = models.ForeignKey(Matiere, on_delete=models.CASCADE)
    enseignant = models.ForeignKey(Enseignant, on_delete=models.CASCADE)
    date = models.DateField()
    
    # classer les enregistrements par classe en plus de les regrouper par jour
def group_by_day_and_class(self):
        return (
            Emploi_du_temps.objects
            .values('jour', 'classe__nom')  # Remarquez 'classe__nom' pour obtenir le nom de la classe
            .annotate(count=count('jour'))
            .order_by('jour', 'classe__nom')  # Remarquez 'classe__nom' ici aussi
        )



class Evaluation(models.Model):
    Type_eva = (
        ('Contrôle', 'Contrôle Continu'),
        ('Exam', 'Examen'),
    )
    classe = models.ForeignKey(Classe, on_delete=models.CASCADE)
    matiere = models.ForeignKey(Matiere, on_delete=models.CASCADE)
    type_d_evaluation = models.CharField(max_length=55, choices=Type_eva)
    note = models.FloatField()
    semestre = models.ForeignKey('Semestre', on_delete=models.CASCADE)
    jour = models.DateTimeField()

class Bulletin(models.Model):
    eleve = models.ForeignKey(Eleve, on_delete=models.CASCADE)
    annee_scolaire = models.ForeignKey('Annee_scolaire', on_delete=models.CASCADE)
    matieres = models.ManyToManyField(Matiere)
    notes = models.FloatField(default=1.0)
    semestre = models.ForeignKey('Semestre', on_delete=models.CASCADE)


class Cycle(models.Model):
    nom = models.CharField(max_length=55, unique=True)
    durée = models.DateField()
    classes = models.ManyToManyField(Classe)

    def __str__(self):
        return self.nom
    

class Annee_scolaire(models.Model):
    debut_annee = models.DateField()
    fin_annee = models.DateField()
    cycles = models.ManyToManyField(Cycle)

class Semestre(models.Model):
    nom = models.CharField(max_length=55, unique=True)
    annee_scolaire = models.ForeignKey(Annee_scolaire, on_delete=models.CASCADE)
    cycles = models.ManyToManyField(Cycle)

    def __str__(self):
        return self.nom

class Absence(models.Model):
    eleves = models.ForeignKey(Eleve, on_delete=models.CASCADE)
    date = models.DateField()
    motif = models.CharField(max_length=200)
    duree = models.DateTimeField()

    def __str__(self):
        return f"{self.eleves} ({self.date}): {self.motif}"

templates/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}

</br></br></br></br>
    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="row">
          <div class="col-lg-6 order-1 order-lg-2" data-aos="fade-left" data-aos-delay="100">
            <img src="{% static 'assets/img/about.jpg' %}" class="img-fluid" alt="">
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content">
            <h3>G-ETAB : Ensemble, construisons un avenir meilleur pour l'éducation au Tchad.</h3>
            <p class="fst-italic">
              L'éducation est un pilier fondamental du développement de toute nation, et la gestion efficace des établissements scolaires joue un rôle clé dans la fourniture d'une éducation de qualité.
            </p>
            <ul>
              <li><i class="bi bi-check-circle"></i> G-ETAB est une plateforme de gestion scolaire numérique qui simplifie la vie des établissements scolaires au Tchad. Elle permet de gérer les élèves, les enseignants et les parents d'élèves de manière efficace et transparente.</li>
              <li><i class="bi bi-check-circle"></i> G-ETAB est un outil précieux pour les établissements scolaires au Tchad. Elle permet d'améliorer la communication et la collaboration entre les différents acteurs de la communauté éducative. Elle contribue également à améliorer la qualité de l'éducation au Tchad.</li>
              <li><i class="bi bi-check-circle"></i> La mise en place de la plateforme G-ETAB est justifiée par la nécessité de moderniser la gestion des établissements scolaires au Tchad.</li>
            </ul>
            <p>
              Cette plateforme a pour objectif d'améliorer l'efficacité de la gestion des écoles au Tchad en offrant des outils modernes pour la collecte, l'analyse et la gestion des données éducatives.
            </p>

          </div>
        </div>

      </div>
    </section><!-- End About Section -->
{% endblock %}

templates/afficher_notes_par_classe.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    </br></br></br>
    <h1>Notes de la classe {{ classe.nom }}</h1>
    <ul>
        {% for eleve in eleves %}
            <li>{{ eleve.nom }}:
                <ul>
                    {% for note in eleve.note_set.all %}
                        <li>{{ note.matiere.nom }} - Note : {{ note.note }}</li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/ajouter_note.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    </br></br></br>
    <h1>Ajouter une note pour {{ eleve.nom }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Ajouter la note</button>
    </form>
    <a href="{% url 'afficher_notes_par_classe' eleve.classe.id %}">Retour à la liste des notes de la classe</a>
    
{% endblock %}

templates/base.html
{% load static %}

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>G-ETAB - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/g-etab.png' %}" rel="icon">
  <link href="{% static 'assets/img/g-etab.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <h1 class="logo me-auto"><a href="index.html">G-ETAB</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="active" href="{% url 'accueil' %}">Accueil</a></li>
          <li><a href="{% url 'liste_matieres' %}">Matieres</a></li>
          <li><a href="{% url 'emploi_du_temps' %}">Emploi du temps</a></li>
          <li><a href="{% url 'liste_evaluations' %}">Evaluations</a></li>
          <li><a href="{% url 'liste_classes' %}">Classes</a></li>
          <li><a href="{% url 'contact' %}">Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

      <a href="{% url 'login' %}" class="get-started-btn">Connexion</a>


    </div>
  </header><!-- End Header -->
  {% block content %}{% endblock  %}

 
  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>G-ETAB</h3>
            <p>
              33JR+QM2, Quartier Walia <br>
              N'djaména, Tchad 00235<br>
              Bemadji-Coding <br><br>
              <strong>Tel:</strong> +235 66-76-37-92<br>
              <strong>Email:</strong> infogetab@gmail.com<br>
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'accueil' %}">Accueil</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'about_page' %}">À propos de nous</a>              </li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'liste_notes' %}">Liste des notes</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Lien Rapide </h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'liste_eleves' %}">Nos Élèves</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'liste_enseignant' %}">Nos Enseignants</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'liste_annees_scolaires' %}">Année Scolaire</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Semestre</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'inscription' %}">Inscription</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Rejoignez notre newsletter</h4>
            <p>Soyez le premier à connaître nos dernières nouveautés en vous abonnant à notre newsletter.</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>

        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Droits d'auteur <strong><span>G-ETAB</span></strong>. Tous droits réservés
        </div>
        <div class="credits">
          Conçu par <a href="https://www.linkedin.com/in/bemadji-ars%C3%A8ne-2184a1178/">Bemadji-Coding</a>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/bulletins.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <h1>Liste des Bulletins</h1>
    <ul>
        {% for bulletin in bulletins %}
            <li>
                <a href="{% url 'detail_bulletin' bulletin.id %}">{{ bulletin.eleve.nom }} - {{ bulletin.annee_scolaire.debut_annee }}/{{ bulletin.annee_scolaire.fin_annee }}</a>
            </li>
        {% empty %}
            <li>Aucun bulletin disponible.</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  </br></br></br></br>
  <main id="main">
      <div class="breadcrumbs" data-aos="fade-in">
        <div class="container">
          <h2>Nous contacter</h2>
          <p>G-ETAB est une plateforme de gestion d'établissement scolaire qui permet de simplifier et de centraliser les tâches administratives. Quia id aut similique quia voluptas sit quaerat debitis. Rerum omnis ipsam aperiam consequatur laboriosam nemo harum praesentium.</p>
        </div>
      </div>
    <div id="carouselExampleRide" class="carousel slide" data-bs-ride="true">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'assets/img/g-etab.png' %}" class="d-block w-100 smaller-image" style="max-width: 500px;" alt="First slide">
        </div>
        <div class="carousel-item">
          <img src="{% static 'assets/img/about3.jpg' %}" class="d-block w-100 smaller-image" style="max-width: 500px;" alt="Second slide">
        </div>
        <div class="carousel-item">
          <img src="{% static 'assets/img/about2.jpeg' %}" class="d-block w-100 smaller-image" style="max-width: 500px;" alt="Third slide">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleRide" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleRide" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    
    <!-- Code HTML du formulaire de contact -->
    <section id="contact" class="contact">
      <div class="container" data-aos="fade-up">
        <div class="row mt-5">
          <div class="col-lg-4">
            <div class="info">
              <div class="address">
                <i class="bi bi-geo-alt"></i>
                <h4>Location:</h4>
                <p>33JR+QM2, Quartier Walia, N'Djamena</p>
              </div>

              <div class="email">
                <i class="bi bi-envelope"></i>
                <h4>Email:</h4>
                <p>getab@mail.com</p>
              </div>

              <div class="phone">
                <i class="bi bi-phone"></i>
                <h4>Tel:</h4>
                <p>+235 66-76-37-92</p>
              </div>
            </div>
          </div>

          <div class="col-lg-8 mt-5 mt-lg-0">
            <form action="forms/contact.php" method="post" role="form" class="php-email-form">
              <div class="row">
                <div class="col-md-6 form-group">
                  <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
                </div>
                <div class="col-md-6 form-group mt-3 mt-md-0">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
                </div>
              </div>
              <div class="form-group mt-3">
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
              </div>
              <div class="form-group mt-3">
                <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
              </div>
              <div class="my-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Votre message a été envoyé. Merci!</div>
              </div>
              <div class="text-center"><button type="submit">Envoyer un message</button></div>
            </form>
          </div>
        </div>
      </div>
    </section>
    <!-- Fin du formulaire de contact -->
  </main>
{% endblock content %}

templates/emploi_du_temps.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    </br></br></br>
    <div class="container">
        <div class="py-4 text-center">
            <h1 class="display-4">Emploi du Temps</h1>
        </div>

        <div class="row">
            <div class="col-10 offset-1">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead class="table-primary">
                            <tr>
                                <th scope="col">Jour</th>
                                <th scope="col">Heures</th>
                                <th scope="col">Matière</th>
                                <th scope="col">Enseignant</th>
                                <th scope="col">Classe</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for emploi in emploi_du_temps %}
                                <tr>
                                    <td>{{ emploi.jour }}</td>
                                    <td>De {{ emploi.heure_debut|time:"H:i" }} à {{ emploi.heure_fin|time:"H:i" }}</td>
                                    <td>{{ emploi.matiere }}</td>
                                    <td>{{ emploi.enseignant }}</td>
                                    <td>Classe: {{ emploi.classe }}</td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="5" class="text-center">Aucun emploi du temps disponible.</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</br></br></br>
{% endblock %}

templates/evaluation.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <title>Évaluations</title>

    {% block content %}
    <h1>Gestion des Évaluations</h1>
    <ul>
        <li><a href="{% url 'liste_evaluations' %}">Liste des Évaluations</a></li>
        <li><a href="{% url 'detail_evaluation' %}">Détail de l'Évaluation</a></li>
    </ul>
    {% endblock %}

templates/inscription_eleve.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <h1>Formulaire d'inscription</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}  <!-- Vous pouvez utiliser as_table, as_ul, ou personnaliser la mise en page comme vous le souhaitez -->
        <button type="submit">S'inscrire</button>
    </form>
    
{% endblock %}